@baseUrl =http://localhost:3000

### MAIN
GET {{baseUrl}}/

### GET ALL USERS
GET {{baseUrl}}/users

### CREATE A USER
POST {{baseUrl}}/users/create
Content-Type: application/json

{
    "name":"med",
    "age": 18
}