@baseUrl =http://localhost:3001
@id = 8158e01d-6b61-4130-8e6f-fbe9e474f7d7

### GET ALL USERS
GET {{baseUrl}}/users

### GET USER BY ID
GET {{baseUrl}}/users/{{id}}

### CREATE A USER
POST {{baseUrl}}/users
Content-Type: application/json

{
    "username":"sidi",
    "email": "sidi@email.com",
    "password": "sidi12345"
}

### UPDATE A USER BY ID
PATCH {{baseUrl}}/users/{{id}}
Content-Type: application/json

{
    "username":"ilayss",
    "email": "ilayss@email.com"
}

### DELETE A USER BY ID
DELETE {{baseUrl}}/users/{{id}}
